### PR TITLE
Rails Project #6 - Milestone 1 #1

### PR DESCRIPTION
**Pull request by pastorp3**
What was made
Created the ERD for the project in the docs folder to implement the feature of friendship between users by the creation of a friendship model

### CODE REVIEW

**Comment by pastorp3** [comment]
Change the target branch as the review suggests

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
### Hello Team 👋
### Status: Changes Required ♻️

Great job so far! 🎉👏
Let's cover some details together ⏬

### Tests

- [x] Please note that we need to add tests in every milestone in this project. Skim through the scaffold to see what you can test and create those test cases please 🙏

### ERD

➡️ We have a couple of things to improve here.

- [x] [OPTIONAL] Naming convention in Rails => if you are referring to the self id, you don't have to put the model's name at the beginning of the id column name. E.g => in the users table, id of a specific user is written like id, but not user_id. If we are in the invitations table and want to refer a user with its id, then we can use that model prefix as user_id. This way you can easily differentiate the columns at one look.

#### Friendship

- [x] Should have two connecting lines to the User model(users table) and please don't miss the PK for this table too. A simple `id` will be enough.

#### Primary Key :key: 
- [x] Currently missing for `likes`, `comments` ( [OPTIONAL] for `friendships`).

## That's it! After making the changes, you can request another code review! 😊
With all my respect... 🙏

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @pastorp3 and @mateomh :lollipop: :balloon: 

### Thank you for doing the changes requested by the previous reviewer, :medal_sports: :medal_sports:  your ERD diagram looks excellent :sparkles:  and you've done a great job adding some unit test cases aswell, let's work on the following changes :construction: :construction_worker: :construction_worker: 

#### Test cases

- [x] I couldn't run your test cases because of this error, let's fix it by properly configure Rspec and Capybara in your project

image

#### Section specific

- [x] your linters have to be configured showing a green checkmark in the last commit of your pull request, seems like your project probably hasn't been activated in [stickler](https://stickler-ci.com/), let's also fix this

#### Milestone #1 docs

- [x] [OPTIONAL] give your friendship user foreign keys meaningful names instead of `user_id1` and `user_id2` it could be `user_id` and `friend_id` respectively

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by pastorp3** [comment]
Add review changes

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED 🍾 
Congratulations on the hard work team. You can continue with the next tasks. 👏 
I wish you all the very best in the next tasks.
##
### Christian Otieno (TSE)

**Pull request merged**
