### PR TITLE
Rails Project #6 - Milestone Friendshipsv2

### PR DESCRIPTION
**Pull request by pastorp3**
What was made
We implement the mutual friendship in the friendship model, so there are two rows for each friendship confirm.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Work @team :clap: :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

 #### Behaviour (Requiered) :warning: 
* [ ] User should be able to reject a friend request.
#### Implementation (required) :warning: 
* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

* [ ] thanks to this, we can find user friends only by user_id in friendships table

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

* [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

* [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

* [ ] in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
* [ ] Use Helpers to reduce the amount of logic inside views (loops, conditionals, querying)
#### N + 1 Queries (OPTIONAL)
* [ ] I encourage you to read about `n+1` and make sure there are no `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5).

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by mateomh** [comment]
The code showed in the review is not our code

**Comment by pastorp3** [comment]
check the server in the terminal and you can see that when you confirm a friend request it update the exist friendship and create an inverse new one

**Review by christianotieno — APPROVED** [review]
# Project Approved 🍾 
Hello team, 👋 great job with the project. Everything looks great, keep it up.
All the required changes have been met in this project. I will therefore go ahead and approve this. 👍 
I wish you all the very best in the nest tasks. 🥇  
##
#### OPTIONAL CHANGES
- Do you mind changing the following  `Cancel Friend Request` 👇  to `Remove Friend` instead?🤔 

 ror-social
##
#### Christian Otieno (TSE)

**Pull request merged**
