### PR TITLE
Rails Project #6 - Milestone Friendshipsv1

### PR DESCRIPTION
**Pull request by pastorp3**
What was made
Created the Friendship model, add methods  to the model, add association the user model and friendship model and create a test for the models

### CODE REVIEW

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @pastorp3  and @mateomh ! 👋 
You have done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [x] You currently do not have the functionality to invite friends. Please make sure that a user can send a friend request. 
Screenshot from pathwright 👇 
Screen Shot 2020-09-16 at 11 28 32 PM
Screenshot from your project showing all users but no way to request friendship 👇 
Screen Shot 2020-09-16 at 11 26 36 PM


- [ ] Please note that the user should also be able to accept and reject friendship requests. 

- [ ] On the timeline, the user should only see their own posts and that of their friends. Yours is currently showing all posts regardless of if they are friends or not. 
screenshot of your timeline 👇 
Screen Shot 2020-09-16 at 11 32 59 PM
screenshot from pathwright 👇 
Screen Shot 2020-09-16 at 11 33 29 PM






****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Good job so far :muscle: However, the required changes mentioned in the previous review are not fully implemented. Check my comments below :point_down:

- **_This is displaying on the web page after the user sign up or sign in:_**
`#<User id: 1, email: "ron@gmail.com", created_at: "2020-09-17 18:14:46", updated_at: "2020-09-17 18:14:46", name: "Ron", gravatar_url: nil>`

- **_When the add_friend is clicked it throws an error:_**
`The action 'Add_friend' could not be found for FriendshipsController`

- **_On the timeline, the user should only see their own posts and that of their friends. Yours is currently showing all posts regardless of if they are friends or not._**

**_Fix these required changes and submit for another review._**

#### _Reviewed by Temitayo Adeleke_

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
* [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] There is a button to invite user to friendship on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by rOluochKe — APPROVED** [review]
Hello,
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

**Pull request merged**
